### PR TITLE
Should apply the render functions only for the "display" purpose

### LINKED ISSUE #837: Numeric columns not sorting properly when using formatCurrency or formatRound in at least versions 0.14 and higher
Hi!

I have found that columns are not sorting properly when applying formatCurrency or formatRound functions, at least from version 0.14 onwards (I detected the error in a machine with version 0.14 installed and then upgraded to version 0.15, version 0.10 works properly on my local machine).

Here is some portion of code to reproduce it:

```{r}
 xfun::session_info('DT')
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS, RStudio 1.2.5001

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=es_ES.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

Package version:
  BH_1.72.0.3          crosstalk_1.0.1.9000 digest_0.6.25        DT_0.15             
  graphics_3.4.4       grDevices_3.4.4      htmltools_0.4.0      htmlwidgets_1.5.1   
  jsonlite_1.6.1       later_1.0.0          lazyeval_0.2.2       magrittr_1.5        
  methods_3.4.4        promises_1.1.0       R6_2.4.1             Rcpp_1.0.3          
  rlang_0.4.5          stats_3.4.4          utils_3.4.4          yaml_2.2.1          
```
```{r}
library(DT)
data <- cbind(1:10000,1:10000)
colnames(data)<-c("A","B")

DT::datatable(data,extensions = c('Buttons','Responsive'), options = list(
  dom = 'Blfrtip',
  buttons = 
    list('copy', 'print', list(
      extend = 'collection',
      buttons = c('csv', 'excel', 'pdf'),
      text = 'Download'
    ))
  
),height="600px"
)%>%formatCurrency(c("A","B"),currency='',digits=0,mark=".",dec=",")
```

And this is how my output looks like when sorting columns:

image

image

Without the formatCurrency function everything seems fine:
image

Can you see anything I'm doing wrong or a known issue that can be related? As I mentioned, it works properly with version 0.10.

---

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.name/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

### PR DESCRIPTION
**Pull request by shrektan**
Closes #837 

See the documentation at https://datatables.net/reference/option/columns.render (the function section)

## CODE (the ORDER column is supposed to be 3,2,1 )

```r
library(DT)
data <- data.frame(
  VALUE = c(998, 999, 1000),
  ORDER = 1:3
)
x <- DT::datatable(data, options = list(order = list(1, 'desc')) ) %>%
  formatCurrency(c("VALUE","ORDER"),currency='',digits=0,mark=".",dec=",")
x
```

### Before 

image

### After

image

### CODE REVIEW

File: R/format.R [hunk 1]
```diff
@@ -196,7 +196,7 @@ colFormatter = function(name, names, rownames = TRUE, template, ...) {
   js = sprintf("
   function(data, type, row, meta) {
     if (type === 'display') {
-      return %s
+      return %s;
```
Comment (shrektan) [inline R/format.R]: Haha, it's not missed because the `template(...)` function will include the `;`

Comment (yihui) [reply R/format.R]: Oh, sorry about that. In that case, I shouldn't use the ternary operator, either. I'll fix it.

Comment (yihui) [reply R/format.R]: Done: bbe6474 (the ternary operator can still be used; I just need to make sure not to add the semicolon)
