### PR TITLE
Be able to control the Selectable range

### LINKED ISSUE #201: Disable select only for certain rows (EDIT: and columns)
Hello everybody,
I would like to ask, if it is possible to disable select only for some rows. I "do" it with a little hack, but maybe there is some smarter way to do it.

server:

``` r
library(shiny)
library(DT)
shinyServer(function(input, output, session) {
    output$foo = DT::renderDataTable( iris )
    proxy = dataTableProxy('foo')
    # observe diabling desired rows
    myClear <- observe({
        # vector of "disabled" rows
        deadList <- c(2,3)
        i_deadList <- input$foo_rows_selected %in% deadList
        if (any(i_deadList)) {
            selectRows(proxy, input$foo_rows_selected[!i_deadList])
        }
    })
})
```

ui:

``` r
library(shiny)
fluidPage(
    DT::dataTableOutput('foo')
)
```

Thank you very much.

EDIT:
I also wonder if there is any way to disable selection functionality for certain column, so if user clicks on a cell in this column, the row is not selected.
Thank you again :)

### LINKED ISSUE #768: FR: Only allow proxy selection (while disable users' ability to select)
I suppose it's debatable whether this is a bug or a feature, but it is not possible to select rows using the proxy if datatable(..., selection="none"). 

I would like to only programmatically select rows in a table. I don't want the user to ever select rows interactively. However, if selection="none", then the console reports that selectRows method is not found.  I want the datatables API functionality of [table.select.style("api")](https://datatables.net/reference/api/select.style()).

This is mysterious to me because I can't access the shinyMethods attribute from the console unless I break inside the datatable-calls customMessageHandler in datatables.js. And I also can't see the datatables methods associated with the Select extension. Is the datatable Select extension even used?

None of these work:
```javascript
$("#table1 .dataTable").DataTable().shinyMethods
$("#table1 .dataTable").DataTable().select.style("api")
$("#table1 .dataTable").DataTable().rows().select()
```

Simple example below.
```r

library(shiny)
library(DT)

ui <- fluidPage(
  actionButton("select_all_1","Select All Rows Table 1"),
  dataTableOutput("table1"),
  actionButton("select_all_2","Select All Rows Table 2"),
  dataTableOutput("table2")
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  table1.proxy <- dataTableProxy("table1")
  table2.proxy <- dataTableProxy("table2")
  observeEvent(input$select_all_1, { 
    selectRows(table1.proxy, 1:3)
  })
  observeEvent(input$select_all_2, { 
    selectRows(table2.proxy, 1:3)
  })
  output$table1 <- renderDT(DT::datatable(data.frame(x=1:3), selection="multiple"))
  output$table2 <- renderDT(DT::datatable(data.frame(y=1:3), selection="none"))
}

# Run the application 
shinyApp(ui = ui, server = server)


```

> xfun::session_info('DT')
> R version 3.5.2 (2018-12-20)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS  10.15.2, RStudio 1.1.463
> 
> Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
> 
> Package version:
>   assertthat_0.2.1   backports_1.1.4    BH_1.69.0.1        cli_1.1.0          colorspace_1.4.0   crayon_1.3.4       crosstalk_1.0.0   
>   digest_0.6.20      DT_0.8.4           ellipsis_0.3.0     fansi_0.4.0        ggplot2_3.1.0      glue_1.3.1         graphics_3.5.2    
>   grDevices_3.5.2    grid_3.5.2         gtable_0.2.0       htmltools_0.3.6    htmlwidgets_1.3    httpuv_1.4.5.1     jsonlite_1.6      
>   labeling_0.3       later_0.8.0        lattice_0.20.38    lazyeval_0.2.1     magrittr_1.5       MASS_7.3.51.1      Matrix_1.2.15     
>   methods_3.5.2      mgcv_1.8.27        mime_0.6           munsell_0.5.0      nlme_3.1.137       pillar_1.4.2       pkgconfig_2.0.2   
>   plyr_1.8.4         promises_1.0.1     R6_2.4.0           RColorBrewer_1.1.2 Rcpp_1.0.1         reshape2_1.4.3     rlang_0.4.4       
>   scales_1.0.0       shiny_1.2.0        sourcetools_0.1.7  splines_3.5.2      stats_3.5.2        stringi_1.3.1      stringr_1.4.0     
>   tibble_2.1.3       tools_3.5.2        utf8_1.1.4         utils_3.5.2        vctrs_0.2.0        viridisLite_0.3.0  withr_2.1.2       
>   xtable_1.8.3       yaml_2.2.0         zeallot_0.1.0   
> 

---

By filing an issue to this repo, I promise that

- [X] I have fully read the issue guide at https://yihui.name/issue/.
- [X] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

### PR DESCRIPTION
**Pull request by shrektan**
Closes #201 
Closes #768 

### TODO

- [x] `target = 'cell'`
- [x] Decide to treat the 0th column (rowname) as "disable". The reasons are:
    1. the 0th column is the row name so our users usually want to "disable" the selection
    1. even if somehow their real intention is to "enable", they can provide the column indices reversely, i.e., "disable" other columns. This is no difficult and no performance issues as the number of columns is usually very limited. 
- [x] `selectable` should support logical values where `TRUE` is default and `FALSE` is to disable all (#768)
- [x] the proxy selection function should gain a new argument `ignore.selectable` to ignore the selectable range (#768)
- [x] should validate `selectable` in `validateSelection()` after #795 being merged
- [x] update inst/example (Will do after reviewed by @yihui) 
- [x] double-check on IE11

### Description

See Details section in `DT::datatable`

> selectable could be NULL, TRUE, FALSE or indices, where NULL and TRUE mean all the table is selectable. When FALSE, it means users can't select the table by the cursor (but they could still be able to select the table via dataTableProxy). If indices, they must be all positive or non-positive values. All positive indices mean only the ranges are selectable while all non-positive indices mean the ranges are not selectable.

### Implementation

Considering the complexity of the selection can be performed (shift selection, proxy selection, etc.), I choose to "de-select" the not-allowed range after the user selects so that the implementation could be more robust.

### Nice-to-have in the future

In addition, it's better to make the "disable" state clearer (at present, the user doesn't know certain ranges are not selectable) but I may not have enough time for this right now, so I incline to leave this in the future when there're real user requests.

### CODE

```r
library(shiny)

ui = fluidPage(sidebarLayout(
  sidebarPanel(
    radioButtons('target', 'target', c('row', 'column', 'row+column', 'cell'), inline = TRUE),
    radioButtons('mode', 'mode', c('multiple', 'single'), inline = TRUE),
    radioButtons('rownames', 'rownames', c('TRUE', 'FALSE'), inline = TRUE),
    textInput('selected', 'selected', 'c(1:5, 30)'),
    textInput('selectable', 'selectable', '-(2:4)'),
    radioButtons('server','server',c('TRUE','FALSE'), inline = TRUE),
    radioButtons('proxy_type', 'proxy_type', c('Rows', 'Columns', 'Cells'), inline = TRUE),
    radioButtons('ignore_selectable','ignore_selectable', c('TRUE','FALSE'), inline = TRUE),
    textInput('proxy_select', 'proxy_select', "3:6"),
    actionButton('proxy_click', 'Click')
  ),
  mainPanel(
    verbatimTextOutput('print'),
    DT::DTOutput('tbl')    
  )
))
server = function(input, output, session) {
  output$tbl = DT::renderDT(
    DT::datatable(iris[1:20,], selection = list(
      target = req(input$target), mode = req(input$mode),
      selected = eval(parse(text = req(input$selected))),
      selectable = eval(parse(text = req(input$selectable)))),
      rownames = as.logical(input$rownames)
    ), server = as.logical(input$server)
  )
  proxy = DT::dataTableProxy('tbl')
  observeEvent(input$proxy_click, try({
    tgt = eval(parse(text = req(input$proxy_select)))
    fun = match.fun(sprintf("select%s", req(input$proxy_type)))
    fun(proxy, tgt, as.logical(input$ignore_selectable))
  }))
  output$print = renderPrint({
    print("rows_selected")
    print(input$tbl_rows_selected)
    print("cols_selected")
    print(input$tbl_columns_selected)
    print("cells_selected")
    print(input$tbl_cells_selected)
  })
}
shiny::runApp(list(ui = ui, server = server), port = 6435)

```

### Checks

- Shift row-selection respects selectable
- Out-of-range selected (pre-selection) doesn't break the code
- selectable `NULL`, `TRUE` and `FALSE` works as expected
- Col and cell selection work expected with or without rownames
- Negative and positive selectable works as expected
- Proxy selection works as expected
- Proxy selection will not keep the previous selection
- All the combination cases on IE11 and for row/column/row+column/cell mode

### CODE REVIEW

**Comment by stanstrup** [comment]
Thanks for this. I have tried to implement it in my app that was using the Select extension before together with some call backs. This is much cleaner. I have also made a callback that greys out non-select-able columns. That seems also to play nice with your version.

A few observations:

1) I don't understand your comments about 0-indexing. Your app seems to show that parameters are passed as 1-indexed anyway.
2) I am having trouble with the java variable. In my own app I have a conditional based on the selection being null or not. That check doesn't work anymore for me. `input.tbl_rows_selected` seems never to be `null` even if `input$tbl_rows_selected` shows `NULL`.

I have added a `conditionalPanel` for testing. Is it me that is doing something wrong or is the java var not really `null` when it is intended to be?

```r
library(shiny)

ui = fluidPage(sidebarLayout(
  sidebarPanel(
    radioButtons('target', 'target', c('row', 'column', 'row+column', 'cell'), inline = TRUE),
    radioButtons('mode', 'mode', c('multiple', 'single'), inline = TRUE),
    textInput('selectable', 'selectable', '-(2:4)'),
    radioButtons('server','server',c('TRUE','FALSE'))
  ),
  mainPanel(
    verbatimTextOutput('print'),
    DT::DTOutput('tbl'),
    
    conditionalPanel(condition = "input.tbl_rows_selected != null",
    div(style="border:solid")
    )
    
  )
))
server = function(input, output, session) {
  output$tbl = DT::renderDT(
    
    
    
    DT::datatable(iris, selection = list(
      target = req(input$target), mode = req(input$mode),
      # selected = eval(parse(text = req(input$selectable))))
      selectable = eval(parse(text = req(input$selectable))))
    ), server = as.logical(input$server)
  )
  output$print = renderPrint({
    print("rows_selected")
    print(input$tbl_rows_selected)
    print("cols_selected")
    print(input$tbl_columns_selected)
    print("cells_selected")
    print(input$tbl_cells_selected)
  })
}
shiny::runApp(list(ui = ui, server = server), port = 6435)
```

**Comment by shrektan** [comment]
@stanstrup 

> I don't understand your comments about 0-indexing. Your app seems to show that parameters are passed as 1-indexed anyway.

Yes, it's 1-indexing but the index for the `rowname` is zero. I mean the very first column without the column name.

image

> I am having trouble with the java variable. In my own app I have a conditional based on the selection being null or not. That check doesn't work anymore for me. input.tbl_rows_selected seems never to be null even if input$tbl_rows_selected shows NULL

It is irrelevant to this PR, isn't it? 

I think you are referring to the Javascript code. Change the `condition` to `input.tbl_rows_selected.length > 0` should fix the issue. I haven't investigated the cause but ti looks like Shiny treats the `NULL` object as a length zero array.

**Comment by shrektan** [comment]
@yihui Ready for the reviews now. It's not a small PR... so no hurries, take your time.

File: R/shiny.R [hunk 1]
```diff
@@ -266,24 +266,36 @@ dataTableProxy = function(
...
 #'   columns (row and column indices, respectively) for cell indices; you may
 #'   use \code{NULL} to clear existing selections
+#' @param ignore.selectable when \code{TRUE} (the default), the "selectable"
+#'   range that's specified by \code{selection = list(selectable= )} will be
+#'   ignored; otherwise, you can't select the "non-selectable" range.
 #' @rdname proxy
 #' @export
-selectRows = function(proxy, selected) {
-  invokeRemote(proxy, 'selectRows', list(I_null(as.integer(selected))))
+selectRows = function(proxy, selected, ignore.selectable = TRUE) {
```
Comment (yihui) [inline R/shiny.R:274]: I wonder if `TRUE` is a reasonable default. If certain rows were specified to be not selectable in `datatable()`, we should probably respect that specification by default (because there might be good reasons why they are not selectable). What do you think?

Comment (shrektan) [reply R/shiny.R:274]: > because there might be good reasons why they are not selectable

I agree.

File: inst/htmlwidgets/datatables.js [hunk 2]
```diff
@@ -964,16 +973,53 @@ HTMLWidgets.widget({
...
+          if (nonselectable) {
+            // should make selectable1 positive
+            selected1 = $(selected1).not(selectable1.map(function(i) { return -i; })).get();
+          } else {
+            selected1 = $(selected1).filter(selectable1).get();
+          }
+        }
+        // Change selected1's value based on selectable1, then
+        // refresh the row selection state according to values in selected1
+        var selectRows = function(ignoreSelectable = false) {
```
[the remark this answers is not in the document]
Comment (shrektan) [reply inst/htmlwidgets/datatables.js]: I should have tested it in IE. No syntax error but it doesn't work. One of the possible reasons is that `selectRows/Columns/Cells` are used as callbacks, where the default argument is used. Anyway, I removed all the default arguments and now it works on IE.

**Comment by shrektan** [comment]
So many combinations drive me crazy. I can't guarantee that I literally covered all the check cases mentioned in the first comment but it should fine.

(In the future we may need to refactor some of the selection related code... it's so complicated now...)
